### ISSUE TITLE
fix: trivial readme link update

### ISSUE THREAD

**Issue by srizvi** [edgedb/nextjs-edgedb-auth-template#5]
Current behavior:
- Go to README.md
- Click the link under Step 2's collapsible: "For more installation options, see the [EdgeDB installation guide](https://edgedb.com/docs/guides/install)."
- Redirects to 404

Expected behavior:
- Go to README.md
- Click the link under Step 2's collapsible...
  - Unsure if it should be: https://docs.edgedb.com/cli OR https://docs.edgedb.com/guides 
- Redirects to the intended page

BTW, EdgeDB looks awesome! Canceled all plans for the weekend.

**Comment by beerose** [comment]
Thank you! Just fixed it
